{% set name = "napari-locan" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 664b36b290989ea851fb65779965897789c04857cad76092c6498a895ebef39c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools-scm >=8
    - wheel
  run:
    - python >={{ python_min }}
    - locan >=0.18
    - matplotlib-base
    - napari
    - napari-matplotlib
    - numpy
    - qtpy

test:
  imports:
    - napari_locan
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pyside2

about:
  home: https://pypi.org/project/napari-locan
  summary: Use locan methods in napari for single-molecule localization microscopy data.
  description: |
    This plugin allows loading, visualizing and analyzing single-molecule localization 
    (SMLM) data. napari-locan is well suited for exploratory data analysis. It 
    implements a subset of methods from locan, a python-based library with code for 
    analyzing SMLM data.
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://napari-locan.readthedocs.io
  dev_url: https://github.com/super-resolution/napari-locan

extra:
  recipe-maintainers:
    - sdoose
